export const MenuItems=[
    {
        title:"FindWork",
        cName:"",
        icon:"",
        path:"/findWork"
    },
    {
        title:"Work",
        cName:"",
        icon:"",
        path:"/work"
    },
    {
        title:"FindResource",
        cName:"",
        icon:"",
        path:"/findResource"
    },
    {
        title:"Help",
        cName:"",
        icon:"",
        path:"/help"
    },
    {
        title:"About",
        cName:"",
        icon:"",
        path:"/about"
    },
    {
        title:"Signup",
        cName:"",
        icon:"",
        path:"/signup"
    },
    {
        title:"Login",
        cName:"",
        icon:"",
        path:"/login"
    },
    {
        title:"Profile",
        cName:"",
        icon:"",
        path:"/profile"
    },
    {
        title:"Example",
        cName:"",
        icon:"",
        path:"/example"
    }
]

